// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddToFavorites(arg1:services.DABTrack):Promise<void>;

export function AddToLibrary(arg1:string,arg2:services.TrackInfo):Promise<void>;

export function CheckDABSession():Promise<boolean>;

export function CheckSpotifySession():Promise<boolean>;

export function ClearAllCache():Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function ClearQueue():Promise<void>;

export function ClearTransferHistory():Promise<void>;

export function CreateDABLibrary(arg1:string,arg2:string,arg3:Array<services.TrackInfo>):Promise<services.TransferStats>;

export function DABLogin(arg1:string,arg2:string):Promise<void>;

export function DeleteLibrary(arg1:string):Promise<void>;

export function DeleteTransferRecord(arg1:string):Promise<void>;

export function DownloadTrack(arg1:services.DABTrack):Promise<string>;

export function GetAlbumByID(arg1:string):Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<services.Config>;

export function GetCurrentUser():Promise<Record<string, any>>;

export function GetDownloadHistory():Promise<Array<services.DownloadItem>>;

export function GetDownloadQueue():Promise<Array<services.DownloadItem>>;

export function GetFavorites():Promise<Array<services.DABTrack>>;

export function GetLibraries():Promise<Array<services.Library>>;

export function GetLibraryDetails(arg1:string):Promise<services.LibraryDetailsResponse>;

export function GetLyrics(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetQueue():Promise<Array<services.DABTrack>>;

export function GetSpotifyPlaylist(arg1:string):Promise<services.PlaylistInfo>;

export function GetStreamURL(arg1:any):Promise<string>;

export function GetTotalCacheSize():Promise<string>;

export function GetTransferHistory():Promise<Array<services.TransferRecord>>;

export function Greet(arg1:string):Promise<string>;

export function Logout():Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function OpenMusicFolder():Promise<void>;

export function RecordTransfer(arg1:services.TransferRecord):Promise<void>;

export function RefreshLibraries():Promise<Array<services.Library>>;

export function RemoveFromFavorites(arg1:string):Promise<void>;

export function RemoveFromLibrary(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SaveGeneralSettings(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveQueue(arg1:Array<services.DABTrack>):Promise<void>;

export function SearchDAB(arg1:string):Promise<Array<services.DABTrack>>;

export function SpotifyLogin():Promise<string>;

export function UpdateLibrary(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
