// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToFavorites(arg1) {
  return window['go']['main']['App']['AddToFavorites'](arg1);
}

export function AddToLibrary(arg1, arg2) {
  return window['go']['main']['App']['AddToLibrary'](arg1, arg2);
}

export function CheckDABSession() {
  return window['go']['main']['App']['CheckDABSession']();
}

export function CheckSpotifySession() {
  return window['go']['main']['App']['CheckSpotifySession']();
}

export function ClearAllCache() {
  return window['go']['main']['App']['ClearAllCache']();
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearQueue() {
  return window['go']['main']['App']['ClearQueue']();
}

export function ClearTransferHistory() {
  return window['go']['main']['App']['ClearTransferHistory']();
}

export function CreateDABLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDABLibrary'](arg1, arg2, arg3);
}

export function DABLogin(arg1, arg2) {
  return window['go']['main']['App']['DABLogin'](arg1, arg2);
}

export function DeleteLibrary(arg1) {
  return window['go']['main']['App']['DeleteLibrary'](arg1);
}

export function DeleteTransferRecord(arg1) {
  return window['go']['main']['App']['DeleteTransferRecord'](arg1);
}

export function DownloadTrack(arg1) {
  return window['go']['main']['App']['DownloadTrack'](arg1);
}

export function GetAlbumByID(arg1) {
  return window['go']['main']['App']['GetAlbumByID'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetDownloadQueue() {
  return window['go']['main']['App']['GetDownloadQueue']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetLibraryDetails(arg1) {
  return window['go']['main']['App']['GetLibraryDetails'](arg1);
}

export function GetLyrics(arg1, arg2) {
  return window['go']['main']['App']['GetLyrics'](arg1, arg2);
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetSpotifyPlaylist(arg1) {
  return window['go']['main']['App']['GetSpotifyPlaylist'](arg1);
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetTotalCacheSize() {
  return window['go']['main']['App']['GetTotalCacheSize']();
}

export function GetTransferHistory() {
  return window['go']['main']['App']['GetTransferHistory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenMusicFolder() {
  return window['go']['main']['App']['OpenMusicFolder']();
}

export function RecordTransfer(arg1) {
  return window['go']['main']['App']['RecordTransfer'](arg1);
}

export function RefreshLibraries() {
  return window['go']['main']['App']['RefreshLibraries']();
}

export function RemoveFromFavorites(arg1) {
  return window['go']['main']['App']['RemoveFromFavorites'](arg1);
}

export function RemoveFromLibrary(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromLibrary'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveGeneralSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveGeneralSettings'](arg1, arg2, arg3);
}

export function SaveQueue(arg1) {
  return window['go']['main']['App']['SaveQueue'](arg1);
}

export function SearchDAB(arg1) {
  return window['go']['main']['App']['SearchDAB'](arg1);
}

export function SetDABAPIBase(arg1) {
  return window['go']['main']['App']['SetDABAPIBase'](arg1);
}

export function SpotifyLogin() {
  return window['go']['main']['App']['SpotifyLogin']();
}

export function UpdateLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateLibrary'](arg1, arg2, arg3, arg4);
}
